name: Test CI

on:
  workflow_dispatch:
    inputs:
      commit_sha:
        description: 'Commit SHA to report coverage for'
        required: false
      pr_number:
        description: 'Release PR Number'
        required: false
      publish_type:
        description: 'Tags of package'
        required: true
        type: choice
        default: 'none'
        options:
          - beta
          - latest
          - none

jobs:
  converage-unitests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
        with:
          ref: ${{ github.ref }}

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: '24'

      - name: Cache dependencies
        id: cache-dependencies
        uses: actions/cache@v5
        with:
          path: ./node_modules
          key: dependencies-${{ runner.os }}-node-${{ hashFiles('./pnpm-lock.yaml') }}

      - name: Install dependencies
        if: steps.cache-dependencies.outputs.cache-hit != 'true'
        run: npm install -g pnpm && pnpm i --frozen-lockfile

      - name: Build
        run: npm run build:dev

      - name: Run tests with coverage
        run: npm run test:coverage

      - name: Upload to Coveralls
        uses: coverallsapp/github-action@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: ./reports/coverage/lcov.info

      - name: Get commit info
        if: inputs.pr_number != ''
        id: commit_info
        run: |
          COMMIT_HASH="$(git rev-parse --short HEAD)"
          COMMIT_URL="https://github.com/${GITHUB_REPOSITORY}/commit/$(git rev-parse HEAD)"
          echo "title=AVA Test Results ([${{ inputs.publish_type }}-${COMMIT_HASH}](${COMMIT_URL}))" >> $GITHUB_OUTPUT

      - name: Run tests with markdown
        if: inputs.pr_number != ''
        run: npm run test:md --title="${{ steps.commit_info.outputs.title }}"

      - name: Generate test report
        if: inputs.pr_number != ''
        id: test_report
        run: |
          echo "comment<<EOF" >> $GITHUB_OUTPUT
          cat ./reports/ava-test.md >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Comment on Release PR
        if: inputs.pr_number != ''
        uses: actions/github-script@v8
        with:
          script: |
            const comment = `${{ steps.test_report.outputs.comment }}`;
            const prNumber = ${{ inputs.pr_number }};
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: prNumber,
              body: comment,
            });

  trigger-build-workflow:
    needs: ['converage-unitests']
    if: inputs.publish_type != 'none'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v8
        with:
          github-token: ${{ secrets.GH_TOKEN }}
          script: |
            const publishType = '${{ inputs.publish_type }}';
            await github.rest.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: 'publish-package.yml',
              ref: 'main',
              inputs: {
                publish_type: publishType,
              }
            })
